version: '3.8'

services:
  frontend:
    image: test:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/jack/data/gpxbase.com.pem:/etc/nginx/ssl/gpxbase.com.pem:ro
      - /home/jack/data/gpxbase.com.key:/etc/nginx/ssl/gpxbase.com.key:ro
    restart: unless-stopped 