services:
  postgis:
    container_name: postgis
    image: postgis/postgis:17-3.5
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - gpxbase-backend-postgisdb:/var/lib/postgresql/data
    env_file: .env
    networks:
      - default
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "0.0.0.0:8001:80"
    env_file: .env
    volumes:
      - ./pgadmin4-server.json:/pgadmin4/servers.json
    depends_on:
      - postgis
    networks:
      - default
    links:
      - postgis:postgis

volumes:
  gpxbase-backend-postgisdb:
  gpxbase-backend-gpxfiles:

networks:
  default:
    name: gpxbase-backend-network