---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpxbase-frontend
  labels:
    app: gpxbase-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpxbase-frontend
  template:
    metadata:
      labels:
        app: gpxbase-frontend
    spec:
      imagePullSecrets:
        - name: azure-host-ghcr-secret
      containers:
        - name: gpxbase-frontend
          image: ghcr.io/jianxuan-li/nau-mcit-693/frontend:__IMAGE_TAG__
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpxbase-backend
  labels:
    app: gpxbase-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpxbase-backend
  template:
    metadata:
      labels:
        app: gpxbase-backend
    spec:
      imagePullSecrets:
        - name: azure-host-ghcr-secret
      containers:
        - name: gpxbase-backend
          image: ghcr.io/jianxuan-li/nau-mcit-693/backend:__IMAGE_TAG__
          ports:
            - containerPort: 80
          env:
            - name: GPX_FILES_DIR
              value: /app/gpx_files
          volumeMounts:
            - name: gpx-files-storage
              mountPath: /app/gpx_files
      volumes:
        - name: gpx-files-storage
          hostPath:
            path: /home/azureuser/data/gpxbase/gpx_files
            type: DirectoryOrCreate