---
apiVersion: v1
kind: Service
metadata:
  name: gpxbase-frontend
spec:
  selector:
    app: gpxbase-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: gpxbase-backend
spec:
  selector:
    app: gpxbase-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP