apiVersion: v1
kind: Service
metadata:
  name: gpxbase-frontend
spec:
  selector:
    app: gpxbase-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443 